# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ccg\Desktop\123\search-text-project\search-text\UI\search.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(572, 752)
        self.folderButton = QtWidgets.QPushButton(Dialog)
        self.folderButton.setGeometry(QtCore.QRect(11, 11, 93, 28))
        self.folderButton.setObjectName("folderButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(11, 46, 391, 16))
        self.label.setObjectName("label")
        self.result_list = QtWidgets.QListWidget(Dialog)
        self.result_list.setGeometry(QtCore.QRect(10, 210, 551, 192))
        self.result_list.setMinimumSize(QtCore.QSize(0, 178))
        self.result_list.setObjectName("result_list")
        self.showcontentButton = QtWidgets.QPushButton(Dialog)
        self.showcontentButton.setGeometry(QtCore.QRect(11, 420, 93, 28))
        self.showcontentButton.setObjectName("showcontentButton")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(11, 460, 156, 19))
        self.checkBox.setObjectName("checkBox")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(11, 490, 551, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(11, 68, 551, 101))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(11, 190, 90, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.folderButton.setText(_translate("Dialog", "选择文件夹"))
        self.label.setText(_translate("Dialog", "请输入要查找的关键词（多个关键词以英文\',\'进行分隔）"))
        self.showcontentButton.setText(_translate("Dialog", "显示内容"))
        self.checkBox.setText(_translate("Dialog", "是否打开pdf并高亮"))
        self.label_2.setText(_translate("Dialog", "搜索结果如下"))
